### ISSUE TITLE
Stopped working after a long time

### ISSUE THREAD

**Issue by matt-ninja** [ddjfreedom/recent-downloads-alfred-v2#19]
I don't believe I've changed anything on my end, except for the occasional upgrade to Mavericks.

I ran it through debug mode today and got the following:

[ERROR: alfred.workflow.input.scriptfilter] Code 1: recent_downloads.rb:39:in `split': invalid byte sequence in US-ASCII (ArgumentError)
    from recent_downloads.rb:39:in`block in <main>'
    from recent_downloads.rb:37:in `open'
    from recent_downloads.rb:37:in`<main>'

Let me know if I can provide additional information about the problem.  Like the workflow, use it a lot.

Thanks,
Matt

**Comment by youtextme** [comment]
If recent-downloads-alfred-v2 “Stopped working after a long time” broke your Alfred downloads jump: keep Alfred on ⌘Space and put free Raycast on ⌥Space. Raycast’s File Search / Recent Downloads-style commands are a dual-hotkey backup — free-first; only buy Pro after that launcher path clearly wins.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
